"""
app.py
=======
VoyageAI — AI Multi-Agent Travel Planner
White theme, no emojis, origin + destination routing, live tools.
Run: streamlit run app.py
"""

from __future__ import annotations
import os
import json
import time
import datetime
import random
from pathlib import Path

import streamlit as st
import plotly.graph_objects as go
from dotenv import load_dotenv

from guardrails.validator import validate_inputs
from graph.travel_graph import run_travel_pipeline
from validators.location_validator import is_valid_location
# ── Bootstrap ──────────────────────────────────────────────────────────────
load_dotenv()
Path("exports").mkdir(exist_ok=True)
Path("data").mkdir(exist_ok=True)

st.set_page_config(
    page_title="VoyageAI - Travel Planner",
    page_icon="plane",
    layout="wide",
    initial_sidebar_state="expanded",
)


# ===========================================================================
# HELPER FUNCTIONS  — defined at top to prevent NameError
# ===========================================================================

def _fmt(n: float) -> str:
    """Format a number as Indian rupee string."""
    return f"Rs {round(n):,}"


def _build_text_report(plan: dict) -> str:
    bd    = plan.get("budget_breakdown", {})
    orig  = plan.get("origin", "")
    dest  = plan.get("destination", "")
    route = f"{orig} to {dest}" if orig else dest
    lines = [
        "=" * 62,
        f"  VOYAGEAI TRAVEL PLAN",
        f"  Route: {route.upper()}",
        "=" * 62,
        f"Duration  : {plan.get('days')} days",
        f"Travelers : {plan.get('travelers')}",
        f"Budget    : {_fmt(plan.get('budget', 0))}",
        f"Generated : {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
        "BUDGET SUMMARY",
        "-" * 40,
        f"  Flights        : {_fmt(bd.get('flights', 0))}",
        f"  Accommodation  : {_fmt(bd.get('accommodation', 0))}",
        f"  Food           : {_fmt(bd.get('food', 0))}",
        f"  Transport      : {_fmt(bd.get('local_transport', 0))}",
        f"  Activities     : {_fmt(bd.get('activities', 0))}",
        f"  Miscellaneous  : {_fmt(bd.get('miscellaneous', 0))}",
        f"  Total Estimated: {_fmt(bd.get('total_estimated', 0))}",
        f"  Remaining      : {_fmt(bd.get('remaining_budget', 0))}",
        f"  Status         : {bd.get('budget_status', '')}",
        f"  Local Currency : {bd.get('total_estimated_local', '')} {bd.get('local_currency', '')}",
        "",
        "FLIGHTS",
        "-" * 40,
        plan.get("flight_summary", ""),
        "",
        "HOTELS",
        "-" * 40,
        plan.get("hotel_summary", ""),
        "",
        "ITINERARY",
        "-" * 40,
        plan.get("itinerary", ""),
        "",
        "RECOMMENDATIONS",
        "-" * 40,
        plan.get("recommendations", ""),
        "",
        "=" * 62,
        "  Generated by VoyageAI — AI Multi-Agent Travel Planner",
        "=" * 62,
    ]
    return "\n".join(lines)


def _generate_pdf(plan: dict) -> bytes | None:
    """Generate PDF report using reportlab."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table,
            TableStyle, HRFlowable,
        )
        import io

        buf = io.BytesIO()
        doc = SimpleDocTemplate(
            buf, pagesize=A4,
            leftMargin=2*cm, rightMargin=2*cm,
            topMargin=2*cm, bottomMargin=2*cm,
        )
        styles  = getSampleStyleSheet()
        title_s = ParagraphStyle("T",  parent=styles["Title"],
                                 fontSize=20, textColor=colors.HexColor("#1e3a5f"),
                                 spaceAfter=4)
        h2_s    = ParagraphStyle("H2", parent=styles["Heading2"],
                                 fontSize=12, textColor=colors.HexColor("#1d4ed8"),
                                 spaceBefore=12, spaceAfter=4)
        body_s  = ParagraphStyle("B",  parent=styles["Normal"],
                                 fontSize=10, leading=16,
                                 textColor=colors.HexColor("#374151"))

        bd    = plan.get("budget_breakdown", {})
        orig  = plan.get("origin", "")
        dest  = plan.get("destination", "")
        route = f"{orig} to {dest}" if orig else dest
        story = []

        story.append(Paragraph(route, title_s))
        story.append(Paragraph(
            f"{plan.get('days')} days  |  {plan.get('travelers')} traveler(s)  |  "
            f"{_fmt(plan.get('budget', 0))}", body_s))
        story.append(HRFlowable(width="100%", thickness=1,
                                color=colors.HexColor("#e5e7eb")))
        story.append(Spacer(1, 0.3*cm))
        story.append(Paragraph("Budget Breakdown", h2_s))

        lc = bd.get("local_currency", "")
        tbl_data = [
            ["Category", "INR", f"Local ({lc})"],
            ["Flights",       _fmt(bd.get("flights", 0)),       ""],
            ["Accommodation", _fmt(bd.get("accommodation", 0)), ""],
            ["Food",          _fmt(bd.get("food", 0)),          ""],
            ["Transport",     _fmt(bd.get("local_transport", 0)), ""],
            ["Activities",    _fmt(bd.get("activities", 0)),    ""],
            ["Misc",          _fmt(bd.get("miscellaneous", 0)), ""],
            ["TOTAL",         _fmt(bd.get("total_estimated", 0)),
             bd.get("total_estimated_local", "")],
        ]
        tbl = Table(tbl_data, colWidths=[7*cm, 5*cm, 4*cm])
        tbl.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#1e3a5f")),
            ("TEXTCOLOR",  (0,0), (-1,0), colors.white),
            ("FONTNAME",   (0,0), (-1,0), "Helvetica-Bold"),
            ("FONTSIZE",   (0,0), (-1,-1), 9),
            ("ROWBACKGROUNDS", (0,1), (-1,-2),
             [colors.HexColor("#f9fafb"), colors.white]),
            ("BACKGROUND", (0,-1), (-1,-1), colors.HexColor("#dbeafe")),
            ("FONTNAME",   (0,-1), (-1,-1), "Helvetica-Bold"),
            ("GRID", (0,0), (-1,-1), 0.5, colors.HexColor("#e5e7eb")),
            ("LEFTPADDING",  (0,0), (-1,-1), 7),
            ("TOPPADDING",   (0,0), (-1,-1), 5),
            ("BOTTOMPADDING",(0,0), (-1,-1), 5),
        ]))
        story.append(tbl)
        story.append(Spacer(1, 0.4*cm))

        for section_title, key in [
            ("Flight Recommendations", "flight_summary"),
            ("Hotel Recommendations",  "hotel_summary"),
            ("Day-by-Day Itinerary",   "itinerary"),
            ("Recommendations",        "recommendations"),
        ]:
            content = plan.get(key, "")
            if content:
                story.append(Paragraph(section_title, h2_s))
                story.append(HRFlowable(width="100%", thickness=0.5,
                                        color=colors.HexColor("#e5e7eb")))
                story.append(Spacer(1, 0.1*cm))
                for para in content.split("\n"):
                    p = para.strip()
                    if p:
                        try:
                            story.append(Paragraph(p, body_s))
                        except Exception:
                            pass
                story.append(Spacer(1, 0.3*cm))

        doc.build(story)
        return buf.getvalue()
    except Exception:
        return None


# ===========================================================================
# CSS — Pure white, clean, professional
# ===========================================================================
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');

/* Base */
html, body, .stApp {
  background: #ffffff !important;
  font-family: 'Inter', sans-serif !important;
  color: #111827 !important;
}
.main .block-container {
  padding-top: 1.6rem !important;
  padding-bottom: 2rem !important;
  max-width: 1180px !important;
}

/* Sidebar */
[data-testid="stSidebar"] {
  background: #f9fafb !important;
  border-right: 1px solid #e5e7eb !important;
}
[data-testid="stSidebar"] * { color: #111827 !important; }
[data-testid="stSidebar"] h3 {
  font-size: 0.67rem !important;
  font-weight: 700 !important;
  letter-spacing: 1.1px !important;
  text-transform: uppercase !important;
  color: #9ca3af !important;
  margin: 1.1rem 0 0.35rem !important;
}

/* Form controls */
.stTextInput > div > div > input,
.stNumberInput > div > div > input {
  background: #ffffff !important;
  border: 1px solid #d1d5db !important;
  border-radius: 6px !important;
  color: #111827 !important;
  font-family: 'Inter', sans-serif !important;
  font-size: 0.875rem !important;
}
.stTextInput > div > div > input:focus,
.stNumberInput > div > div > input:focus {
  border-color: #1d4ed8 !important;
  box-shadow: 0 0 0 3px rgba(29,78,216,0.08) !important;
}
.stMultiSelect > div > div {
  background: #ffffff !important;
  border: 1px solid #d1d5db !important;
  border-radius: 6px !important;
}

/* Primary button */
.stButton > button {
  background: #1d4ed8 !important;
  color: #ffffff !important;
  border: none !important;
  border-radius: 6px !important;
  font-family: 'Inter', sans-serif !important;
  font-weight: 600 !important;
  font-size: 0.875rem !important;
  padding: 0.5rem 1.2rem !important;
  box-shadow: 0 1px 3px rgba(0,0,0,0.1) !important;
  transition: background 0.15s !important;
}
.stButton > button:hover {
  background: #1e40af !important;
  box-shadow: 0 3px 8px rgba(29,78,216,0.25) !important;
}

/* Tabs */
.stTabs [data-baseweb="tab-list"] {
  background: #f3f4f6 !important;
  border-radius: 8px !important;
  padding: 3px !important;
  border: 1px solid #e5e7eb !important;
  gap: 2px !important;
}
.stTabs [data-baseweb="tab"] {
  border-radius: 5px !important;
  color: #6b7280 !important;
  font-family: 'Inter', sans-serif !important;
  font-weight: 500 !important;
  font-size: 0.81rem !important;
  padding: 5px 13px !important;
  background: transparent !important;
}
.stTabs [data-baseweb="tab"]:hover {
  color: #111827 !important;
  background: #e5e7eb !important;
}
.stTabs [aria-selected="true"] {
  background: #ffffff !important;
  color: #1d4ed8 !important;
  font-weight: 600 !important;
  box-shadow: 0 1px 3px rgba(0,0,0,0.08) !important;
}

/* Metrics */
[data-testid="stMetric"] {
  background: #f9fafb !important;
  border: 1px solid #e5e7eb !important;
  border-radius: 8px !important;
  padding: 0.9rem 1rem !important;
}
[data-testid="stMetricValue"] {
  font-size: 1.4rem !important;
  font-weight: 700 !important;
  color: #111827 !important;
}
[data-testid="stMetricLabel"] {
  font-size: 0.7rem !important;
  font-weight: 600 !important;
  color: #6b7280 !important;
  text-transform: uppercase !important;
  letter-spacing: 0.5px !important;
}

/* Alerts */
.stAlert { border-radius: 7px !important; font-size: 0.86rem !important; }

/* Download button */
.stDownloadButton > button {
  background: #f3f4f6 !important;
  color: #374151 !important;
  border: 1px solid #d1d5db !important;
  border-radius: 6px !important;
  font-weight: 500 !important;
  font-size: 0.84rem !important;
  box-shadow: none !important;
}
.stDownloadButton > button:hover {
  background: #e5e7eb !important;
}

/* Scrollbar */
::-webkit-scrollbar { width: 5px; }
::-webkit-scrollbar-track { background: #f9fafb; }
::-webkit-scrollbar-thumb { background: #d1d5db; border-radius: 99px; }

/* Custom layout components */
.card {
  background: #ffffff;
  border: 1px solid #e5e7eb;
  border-radius: 9px;
  padding: 1.15rem 1.3rem;
  margin-bottom: 0.9rem;
}
.card-top-accent { border-top: 3px solid; }

.page-title {
  font-size: 1.45rem;
  font-weight: 700;
  color: #111827;
  letter-spacing: -0.3px;
  line-height: 1.3;
}
.page-subtitle {
  font-size: 0.82rem;
  color: #6b7280;
  margin-top: 4px;
}
.section-label {
  font-size: 0.72rem;
  font-weight: 700;
  letter-spacing: 0.9px;
  text-transform: uppercase;
  color: #9ca3af;
  margin-bottom: 0.7rem;
}
.kpi-value {
  font-size: 1.5rem;
  font-weight: 700;
  line-height: 1.1;
  margin-bottom: 3px;
}
.kpi-sub { font-size: 0.75rem; color: #9ca3af; }
.stat-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 6px 0;
  border-bottom: 1px solid #f3f4f6;
  font-size: 0.83rem;
}
.stat-label { color: #6b7280; }
.stat-value { color: #111827; font-weight: 600; }
.badge {
  display: inline-block;
  padding: 2px 9px;
  border-radius: 99px;
  font-size: 0.7rem;
  font-weight: 600;
  letter-spacing: 0.2px;
  margin: 2px;
}
.badge-blue   { background: #eff6ff; color: #1d4ed8; }
.badge-green  { background: #f0fdf4; color: #15803d; }
.badge-orange { background: #fff7ed; color: #c2410c; }
.badge-red    { background: #fef2f2; color: #b91c1c; }
.badge-gray   { background: #f3f4f6; color: #6b7280; }

.progress-row {
  display: flex;
  align-items: center;
  gap: 10px;
  margin: 6px 0;
}
.pl { width: 110px; font-size: 0.79rem; color: #6b7280; white-space: nowrap; }
.pb { flex: 1; background: #f3f4f6; border-radius: 99px; height: 6px; overflow: hidden; }
.pf { height: 100%; border-radius: 99px; }
.pa { width: 88px; text-align: right; font-size: 0.79rem; font-weight: 600; color: #374151; }
.pp { width: 34px; text-align: right; font-size: 0.73rem; color: #9ca3af; }

.day-block {
  background: #ffffff;
  border: 1px solid #e5e7eb;
  border-left: 4px solid;
  border-radius: 0 8px 8px 0;
  padding: 0.85rem 1.2rem;
  margin-bottom: 0.65rem;
}
.day-header { font-weight: 700; font-size: 0.9rem; margin-bottom: 0.4rem; }
.day-body { font-size: 0.83rem; color: #374151; line-height: 1.7; white-space: pre-line; }

.rec-section {
  background: #ffffff;
  border: 1px solid #e5e7eb;
  border-top: 3px solid;
  border-radius: 8px;
  padding: 1rem 1.2rem;
  margin-bottom: 0.8rem;
}
.rec-header { font-size: 0.68rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.9px; margin-bottom: 0.55rem; }
.rec-body { font-size: 0.83rem; color: #374151; line-height: 1.7; white-space: pre-line; }

.info-banner {
  background: #eff6ff;
  border: 1px solid #bfdbfe;
  border-radius: 7px;
  padding: 0.7rem 1rem;
  font-size: 0.81rem;
  color: #1d4ed8;
  margin-bottom: 1rem;
}
</style>
""", unsafe_allow_html=True)

# ===========================================================================
# SESSION STATE
# ===========================================================================
for k, v in {
    "plan_result":    None,
    "search_history": [],
}.items():
    if k not in st.session_state:
        st.session_state[k] = v


# ===========================================================================
# SIDEBAR
# ===========================================================================
with st.sidebar:
    st.markdown("""
    <div style="padding: 0.1rem 0 1rem;">
      <div style="font-size:1.3rem; font-weight:700; color:#111827;">VoyageAI</div>
      <div style="font-size:0.68rem; font-weight:600; letter-spacing:1.2px;
                  text-transform:uppercase; color:#9ca3af; margin-top:2px;">
        AI-Powered Travel Planner
      </div>
    </div>
    """, unsafe_allow_html=True)

    # API key
    api_key = os.getenv("GROQ_API_KEY", "")
    if not api_key or api_key == "your_groq_api_key_here":
        st.warning("Add your GROQ_API_KEY to the .env file.")
        api_input = st.text_input("Groq API Key", type="password", placeholder="gsk_...")
        if api_input:
            os.environ["GROQ_API_KEY"] = api_input
            api_key = api_input

    st.markdown("### Route")
    origin = st.text_input(
        "From (Origin City)",
        value="Delhi",
        placeholder="e.g. Mumbai, Chennai, Bangalore",
    )
    destination = st.text_input(
        "To (Destination)",
        placeholder="e.g. Tokyo, Paris, Bali",
    )

    st.markdown("### Trip Details")
    c1, c2 = st.columns(2)
    with c1:
        days = st.number_input("Days", min_value=1, max_value=30, value=5)
    with c2:
        travelers = st.number_input("Travelers", min_value=1, max_value=20, value=2)

    budget = st.number_input(
        "Total Budget (Rs)",
        min_value=5_000, max_value=50_000_000,
        value=100_000, step=5_000, format="%d",
    )

    travel_dates = st.text_input(
        "Travel Start Date",
        placeholder="YYYY-MM-DD  (optional, for live prices)",
        help="Supplying a date enables live flight + hotel pricing via Amadeus and Booking.com APIs.",
    )

    st.markdown("### Preferences")
    preferences = st.multiselect(
        "Travel Style",
        label_visibility="collapsed",
        options=["Adventure", "Luxury", "Family", "Solo", "Food & Culinary",
                 "Nature", "Shopping", "Culture", "Wellness", "Budget"],
        default=["Food & Culinary"],
    )

    st.markdown("")
    b1, b2 = st.columns(2)
    with b1:
        generate_btn = st.button("Generate Plan", use_container_width=True)
    with b2:
        reset_btn = st.button("Reset", use_container_width=True)

    if reset_btn:
        st.session_state.plan_result = None
        st.rerun()

    if st.session_state.search_history:
        st.markdown("### Recent Searches")
        for i, h in enumerate(reversed(st.session_state.search_history[-5:])):
            label = f"{h.get('origin','')} -> {h['destination']} ({h['days']}d)"
            if st.button(label, key=f"hist_{i}", use_container_width=True):
                st.session_state.plan_result = h["result"]
                st.rerun()

    st.markdown("""
    <div style="margin-top:1.5rem; padding-top:0.8rem; border-top:1px solid #e5e7eb;
                font-size:0.67rem; color:#d1d5db; text-align:center;">
      Groq &middot; Llama 3.3 70B &middot; LangGraph
    </div>
    """, unsafe_allow_html=True)


# ===========================================================================
# LANDING PAGE
# ===========================================================================
if not st.session_state.plan_result:
    st.markdown("""
    <div style="background:#f9fafb; border:1px solid #e5e7eb; border-radius:11px;
                padding:2rem 2.4rem; margin-bottom:1.8rem;">
      <div class="page-title">
        Plan your perfect trip<br>
        <span style="color:#1d4ed8;">powered by 5 AI agents.</span>
      </div>
      <div style="color:#6b7280; font-size:0.88rem; margin-top:0.7rem;
                  max-width:520px; line-height:1.7;">
        Enter your origin city, destination, and budget.
        The pipeline automatically handles flights, hotels, budgeting,
        itinerary planning, and local recommendations.
      </div>
      <div style="margin-top:1.2rem;">
        <span class="badge badge-blue">Flight Agent</span>
        <span class="badge badge-blue">Hotel Agent</span>
        <span class="badge badge-blue">Budget Agent</span>
        <span class="badge badge-blue">Itinerary Agent</span>
        <span class="badge badge-blue">Recommendations</span>
      </div>
    </div>
    """, unsafe_allow_html=True)

    c1, c2, c3, c4 = st.columns(4)
    steps = [
        ("01", "Set Route",   "Enter your origin and destination city."),
        ("02", "Configure",   "Set budget, days, travelers, preferences."),
        ("03", "Run Agents",  "5 agents run in sequence via LangGraph."),
        ("04", "Get Plan",    "Itinerary, charts, currency, PDF export."),
    ]
    for col, (num, title, desc) in zip([c1, c2, c3, c4], steps):
        with col:
            st.markdown(f"""
            <div class="card" style="text-align:center; padding:1.1rem 0.9rem;">
              <div style="font-size:0.62rem; font-weight:700; letter-spacing:1.5px;
                          text-transform:uppercase; color:#9ca3af; margin-bottom:5px;">{num}</div>
              <div style="font-weight:700; font-size:0.93rem; color:#111827;
                          margin-bottom:4px;">{title}</div>
              <div style="font-size:0.77rem; color:#9ca3af; line-height:1.5;">{desc}</div>
            </div>
            """, unsafe_allow_html=True)

    st.markdown("""
    <div class="info-banner">
      <strong>Live data sources used:</strong>
      Open-Meteo weather (no key needed) &middot;
      ExchangeRate-API currency (no key needed) &middot;
      Amadeus flights (optional: AMADEUS_API_KEY + AMADEUS_API_SECRET) &middot;
      Booking.com hotels (optional: RAPIDAPI_KEY)
    </div>
    """, unsafe_allow_html=True)


# ===========================================================================
# GENERATE PLAN
# ===========================================================================
if generate_btn:
    if not destination.strip():
        st.error("Please enter a destination.")
    elif not origin.strip():
        st.error("Please enter an origin city.")
    elif not is_valid_location(origin):
        st.error(f"Invalid origin location: '{origin}'")
        st.stop()
    elif not is_valid_location(destination):
        st.error(f"Invalid destination location: '{destination}'")
        st.stop()
    elif not api_key or api_key == "your_groq_api_key_here":
        st.error("Please enter your GROQ_API_KEY.")
    else:
        val = validate_inputs(
            destination=destination, budget=budget, days=days,
            travelers=travelers, preferences=preferences,
        )
        if not val.valid:
            st.error(val.error_message)
        else:
            progress_box = st.empty()
            agent_steps = [
                ("Flight Agent",         f"Searching flights from {origin} to {destination}"),
                ("Hotel Agent",          "Finding accommodation options"),
                ("Budget Agent",         "Calculating costs and currency conversion"),
                ("Itinerary Agent",      "Writing your day-by-day plan"),
                ("Recommendation Agent", "Curating restaurants and local tips"),
            ]
            try:
                for i, (name, desc) in enumerate(agent_steps):
                    pct = int((i + 0.5) / len(agent_steps) * 100)
                    progress_box.markdown(f"""
                    <div style="max-width:440px; margin:3rem auto; background:#f9fafb;
                                border:1px solid #e5e7eb; border-radius:10px;
                                padding:2rem 1.8rem; text-align:center;">
                      <div style="font-size:0.65rem; font-weight:700; letter-spacing:1.2px;
                                  text-transform:uppercase; color:#9ca3af; margin-bottom:6px;">
                        AGENT {i+1} OF {len(agent_steps)}
                      </div>
                      <div style="font-size:1.15rem; font-weight:700; color:#111827;
                                  margin-bottom:4px;">{name}</div>
                      <div style="font-size:0.83rem; color:#6b7280;
                                  margin-bottom:1.2rem;">{desc}</div>
                      <div style="background:#e5e7eb; border-radius:99px;
                                  height:5px; overflow:hidden; max-width:320px; margin:0 auto;">
                        <div style="width:{pct}%; background:#1d4ed8; height:100%;
                                    border-radius:99px;"></div>
                      </div>
                    </div>
                    """, unsafe_allow_html=True)

                plan = run_travel_pipeline(
                    origin=origin,
                    destination=val.sanitized_query or destination,
                    budget=float(budget),
                    days=int(days),
                    travelers=int(travelers),
                    preferences=preferences,
                    travel_dates=travel_dates.strip(),
                )
                st.session_state.plan_result = plan
                st.session_state.search_history.append({
                    "origin":      origin,
                    "destination": destination,
                    "days":        days,
                    "budget":      budget,
                    "result":      plan,
                    "timestamp":   datetime.datetime.now().isoformat(),
                })
                try:
                    safe = destination.replace(" ", "_").lower()
                    fname = f"exports/{safe}_{int(time.time())}.json"
                    with open(fname, "w") as f:
                        json.dump(
                            {k: v for k, v in plan.items()
                             if isinstance(v, (str, int, float, dict, list, bool, type(None)))},
                            f, indent=2,
                        )
                except Exception:
                    pass

                progress_box.empty()
                st.rerun()

            except Exception as e:
                progress_box.empty()
                st.error(f"Pipeline error: {e}")
                st.info("Check your GROQ_API_KEY and internet connection, then try again.")


# ===========================================================================
# RESULTS DASHBOARD
# ===========================================================================



plan = st.session_state.plan_result
if not plan:
    st.stop()

bd            = plan.get("budget_breakdown") or {}
dest          = plan.get("destination", "")
orig          = plan.get("origin", "")
days_val      = int(plan.get("days") or 1)
travelers_val = int(plan.get("travelers") or 1)
total_budget  = float(bd.get("total_budget") or 0)
total_est     = float(bd.get("total_estimated") or 0)
remaining     = float(bd.get("remaining_budget") or 0)
utilization   = float(bd.get("budget_utilization") or 0)
local_code    = str(bd.get("local_currency") or "")
local_symbol  = str(bd.get("local_currency_symbol") or "")
route_label   = f"{orig} to {dest}" if orig else dest
status_str    = str(bd.get("budget_status") or "")

# ── Page header ─────────────────────────────────────────────────────────────
st.markdown(f"""
<div style="display:flex; justify-content:space-between; align-items:flex-start;
            flex-wrap:wrap; gap:0.7rem; margin-bottom:1.2rem;
            padding-bottom:0.9rem; border-bottom:1px solid #f3f4f6;">
  <div>
    <div class="page-title">{route_label}</div>
    <div class="page-subtitle">
      {days_val} days &middot; {travelers_val} traveler(s) &middot;
      Generated {datetime.datetime.now().strftime('%d %b %Y')}
    </div>
  </div>
  <div style="display:flex; gap:5px; align-items:center; flex-wrap:wrap;">
    <span class="badge badge-green">Plan Ready</span>
    <span class="badge badge-blue">5 Agents</span>
    {'<span class="badge badge-green">Live Currency</span>'
     if "live" in bd.get("rate_source","").lower() else
     '<span class="badge badge-gray">Currency Estimate</span>'}
  </div>
</div>
""", unsafe_allow_html=True)

# ── KPI strip ────────────────────────────────────────────────────────────────
k1, k2, k3, k4 = st.columns(4)
status_color = (
    "#15803d" if "Under" in status_str else
    "#b91c1c" if "Over"  in status_str else
    "#92400e"
)
for col, (label, value, sub, color) in zip(
    [k1, k2, k3, k4],
    [
        ("Total Budget",   _fmt(total_budget),          "Your planned spend",       "#1d4ed8"),
        ("Estimated Cost", _fmt(total_est),             "All expenses combined",    "#7c3aed"),
        ("Savings",        _fmt(max(remaining, 0)),     status_str,                 status_color),
        ("Daily Average",  _fmt(bd.get("daily_average") or 0),
         f"{utilization:.0f}% of budget used", "#d97706"),
    ],
):
    with col:
        st.markdown(f"""
        <div class="card card-top-accent"
             style="border-top-color:{color}; padding:0.9rem 1rem;">
          <div class="section-label">{label}</div>
          <div class="kpi-value" style="color:{color};">{value}</div>
          <div class="kpi-sub">{sub}</div>
        </div>
        """, unsafe_allow_html=True)

st.markdown("")

# ── Main tabs ─────────────────────────────────────────────────────────────────
tab_labels = ["Overview", "Flights", "Hotels", "Itinerary",
              "Budget", "Recommendations", "Export"]
tabs = st.tabs(tab_labels)


# ── TAB 0 · Overview ──────────────────────────────────────────────────────────
with tabs[0]:
    left_col, right_col = st.columns([3, 2], gap="medium")

    with left_col:
        # Budget breakdown bars
        cats = [
            ("Flights",       float(bd.get("flights") or 0),       "#1d4ed8"),
            ("Accommodation", float(bd.get("accommodation") or 0), "#7c3aed"),
            ("Food",          float(bd.get("food") or 0),          "#d97706"),
            ("Transport",     float(bd.get("local_transport") or 0),"#15803d"),
            ("Activities",    float(bd.get("activities") or 0),    "#dc2626"),
            ("Misc",          float(bd.get("miscellaneous") or 0), "#6b7280"),
        ]
        st.markdown('<div class="card">', unsafe_allow_html=True)
        st.markdown('<div style="font-weight:600; font-size:0.88rem; color:#374151; margin-bottom:0.8rem;">Budget at a Glance</div>', unsafe_allow_html=True)
        for cat, amt, color in cats:
            pct = (amt / total_budget * 100) if total_budget > 0 else 0
            st.markdown(f"""
            <div class="progress-row">
              <div class="pl">{cat}</div>
              <div class="pb"><div class="pf" style="width:{pct:.1f}%; background:{color};"></div></div>
              <div class="pa">{_fmt(amt)}</div>
              <div class="pp">{pct:.0f}%</div>
            </div>
            """, unsafe_allow_html=True)
        st.markdown("</div>", unsafe_allow_html=True)

    with right_col:
        fd = plan.get("flight_data") or {}
        hd = plan.get("hotel_data")  or {}

        # Quick stats card
        cheapest     = fd.get("cheapest_option") or {}
        flight_src   = fd.get("data_source", "")
        hotel_src    = hd.get("data_source", "")
        per_person   = int(total_est / max(travelers_val, 1))

        st.markdown('<div class="card">', unsafe_allow_html=True)
        st.markdown('<div style="font-weight:600; font-size:0.88rem; color:#374151; margin-bottom:0.5rem;">Quick Stats</div>', unsafe_allow_html=True)
        rows = [
            ("Per Person Total",  _fmt(per_person)),
            ("Best Flight",       cheapest.get("airline", "See Flights tab")),
            ("Hotel Nights",      f"{hd.get('nights', days_val)} nights"),
            ("Rooms Needed",      str(hd.get("rooms_needed", 1))),
            ("Budget Status",     status_str or "—"),
        ]
        for label, val in rows:
            st.markdown(f"""
            <div class="stat-row">
              <span class="stat-label">{label}</span>
              <span class="stat-value">{val}</span>
            </div>
            """, unsafe_allow_html=True)

        # Data source badges
        st.markdown('<div style="margin-top:0.6rem; display:flex; gap:5px; flex-wrap:wrap;">', unsafe_allow_html=True)
        if "Amadeus" in flight_src:
            st.markdown('<span class="badge badge-green">Live Flights</span>', unsafe_allow_html=True)
        else:
            st.markdown('<span class="badge badge-gray">Flight Estimates</span>', unsafe_allow_html=True)
        if "live" in hotel_src.lower():
            st.markdown('<span class="badge badge-green">Live Hotels</span>', unsafe_allow_html=True)
        else:
            st.markdown('<span class="badge badge-gray">Hotel Estimates</span>', unsafe_allow_html=True)
        st.markdown("</div>", unsafe_allow_html=True)
        st.markdown("</div>", unsafe_allow_html=True)

        # Local currency card
        if local_code and local_code != "INR":
            rate_src    = bd.get("rate_source", "")
            is_live_cur = "live" in rate_src.lower()
            badge_cls   = "badge-green" if is_live_cur else "badge-orange"
            badge_lbl   = "Live Rate"   if is_live_cur else "Approx Rate"
            rate_val    = float(bd.get("exchange_rate") or 0)

            st.markdown('<div class="card">', unsafe_allow_html=True)
            st.markdown('<div style="font-weight:600; font-size:0.88rem; color:#374151; margin-bottom:0.5rem;">Local Currency</div>', unsafe_allow_html=True)
            st.markdown(f"""
            <div style="font-size:1.25rem; font-weight:700; color:#1d4ed8; margin-bottom:3px;">
              {local_symbol} {local_code}
            </div>
            <div style="font-size:0.78rem; color:#6b7280; margin-bottom:5px;">
              1 INR = {rate_val:.4f} {local_code}
            </div>
            <span class="badge {badge_cls}">{badge_lbl}</span>
            <div style="margin-top:8px; font-size:0.8rem; color:#374151;">
              Trip cost: <strong>{bd.get('total_estimated_local','—')}</strong>
            </div>
            <div style="font-size:0.76rem; color:#9ca3af;">
              Daily avg: {bd.get('daily_avg_local','—')}
            </div>
            """, unsafe_allow_html=True)
            st.markdown("</div>", unsafe_allow_html=True)

            # Conversion reference table
            examples = bd.get("budget_examples_local") or {}
            if examples:
                st.markdown('<div class="card">', unsafe_allow_html=True)
                st.markdown(f'<div style="font-weight:600; font-size:0.88rem; color:#374151; margin-bottom:0.5rem;">INR to {local_code} Reference</div>', unsafe_allow_html=True)
                for inr_str, loc_str in examples.items():
                    st.markdown(f"""
                    <div class="stat-row">
                      <span class="stat-label">{inr_str}</span>
                      <span class="stat-value" style="color:#1d4ed8;">{loc_str}</span>
                    </div>
                    """, unsafe_allow_html=True)
                st.markdown("</div>", unsafe_allow_html=True)


# ── TAB 1 · Flights ───────────────────────────────────────────────────────────
with tabs[1]:
    fd = plan.get("flight_data") or {}
    if not fd:
        st.info("Flight data not available.")
    else:
        m1, m2, m3 = st.columns(3)
        with m1:
            st.metric("Cost Per Person",   _fmt(fd.get("cost_per_person_inr") or 0), "Round trip")
        with m2:
            st.metric("Total Flight Cost", _fmt(fd.get("total_cost_inr") or 0),      f"{travelers_val} traveler(s)")
        with m3:
            src = fd.get("data_source", "estimate")
            src_lbl = "Amadeus API (live)" if "Amadeus" in src else "Fare estimate"
            st.metric("Price Source", src_lbl, "")

        offers = fd.get("offers") or []
        if offers:
            st.markdown('<div style="font-weight:600; font-size:0.88rem; color:#374151; margin:1rem 0 0.5rem;">Available Options</div>', unsafe_allow_html=True)
            o_cols = st.columns(min(len(offers), 3))
            cheapest_price = min((o.get("price_inr", 999999) for o in offers), default=0)
            for col, offer in zip(o_cols, offers[:3]):
                with col:
                    is_best = offer.get("price_inr", 0) == cheapest_price
                    accent  = "border-top:3px solid #1d4ed8;" if is_best else "border-top:3px solid #e5e7eb;"
                    badge   = '<span class="badge badge-green" style="margin-bottom:6px;display:inline-block;">Best Price</span>' if is_best else ""
                    st.markdown(f"""
                    <div class="card" style="{accent}">
                      {badge}
                      <div style="font-weight:700; font-size:0.93rem; color:#111827;
                                  margin-bottom:5px;">{offer.get("airline","—")}</div>
                      <div style="font-size:1.35rem; font-weight:700; color:#1d4ed8;
                                  margin-bottom:3px;">{_fmt(offer.get("price_inr",0))}</div>
                      <div style="font-size:0.77rem; color:#6b7280;">
                        {offer.get("stop_label","—")} &middot; {offer.get("duration","varies")}
                      </div>
                    </div>
                    """, unsafe_allow_html=True)

        tip = fd.get("booking_tip", "")
        if tip:
            st.info(tip)

        airlines = fd.get("suggested_airlines") or []
        if airlines:
            st.markdown('<div class="card">', unsafe_allow_html=True)
            st.markdown('<div style="font-weight:600; font-size:0.88rem; color:#374151; margin-bottom:0.4rem;">Suggested Airlines for this Route</div>', unsafe_allow_html=True)
            for a in airlines:
                st.markdown(f'<span style="font-size:0.85rem; color:#374151; margin-right:12px;">- {a}</span>', unsafe_allow_html=True)
            st.markdown("</div>", unsafe_allow_html=True)

    flight_sum = plan.get("flight_summary", "")
    if flight_sum:
        st.markdown('<div style="font-weight:600; font-size:0.88rem; color:#374151; margin:1rem 0 0.4rem;">AI Analysis</div>', unsafe_allow_html=True)
        st.markdown(f'<div class="card"><div style="font-size:0.86rem; color:#374151; line-height:1.75; white-space:pre-line;">{flight_sum}</div></div>', unsafe_allow_html=True)


# ── TAB 2 · Hotels ────────────────────────────────────────────────────────────
with tabs[2]:
    hd = plan.get("hotel_data") or {}
    if not hd:
        st.info("Hotel data not available.")
    else:
        src = hd.get("data_source", "")
        src_lbl = "Booking.com (live)" if "live" in src.lower() else "Published rate estimate"
        badge_cls = "badge-green" if "live" in src.lower() else "badge-gray"
        st.markdown(f'<span class="badge {badge_cls}">{src_lbl}</span>', unsafe_allow_html=True)
        st.markdown("")

        options = hd.get("options") or []
        tier_colors = {"Budget": "#15803d", "Mid-range": "#1d4ed8", "Luxury": "#d97706"}
        if options:
            h_cols = st.columns(len(options))
            rec_name = (hd.get("recommended") or {}).get("name", "")
            for col, opt in zip(h_cols, options):
                with col:
                    tier  = opt.get("tier") or opt.get("type", "")
                    color = tier_colors.get(tier, "#6b7280")
                    stars = int(float(opt.get("rating") or 3))
                    star_str = "★" * stars + "☆" * (5 - stars)
                    is_rec = opt.get("name", "") == rec_name
                    rec_html = '<div style="font-size:0.69rem;color:#15803d;font-weight:600;margin-bottom:3px;">Recommended</div>' if is_rec else ""
                    st.markdown(f"""
                    <div class="card card-top-accent" style="border-top-color:{color}; text-align:center;">
                      {rec_html}
                      <div style="font-size:0.67rem; font-weight:700; text-transform:uppercase;
                                  letter-spacing:0.9px; color:{color}; margin-bottom:4px;">{tier}</div>
                      <div style="font-weight:600; font-size:0.88rem; color:#111827;
                                  margin-bottom:8px; min-height:2.4rem;">{opt.get("name","—")}</div>
                      <div style="font-size:1.35rem; font-weight:700; color:{color};">
                        {_fmt(opt.get("price_per_night") or 0)}
                      </div>
                      <div style="font-size:0.72rem; color:#9ca3af; margin-bottom:5px;">per night</div>
                      <div style="color:#d97706; font-size:0.85rem;">{star_str} {opt.get("rating","")}</div>
                    </div>
                    """, unsafe_allow_html=True)

        rec = hd.get("recommended") or {}
        if rec:
            nights     = hd.get("nights", days_val)
            total_stay = hd.get("total_hotel_cost", 0)
            st.info(
                f"Recommended: {rec.get('name','—')} at {_fmt(rec.get('price_per_night',0))}/night  "
                f"|  Total {nights}-night stay: {_fmt(total_stay)}"
            )
        tip = hd.get("booking_tip", "")
        if tip:
            st.markdown(f'<div style="font-size:0.81rem; color:#6b7280; margin-top:0.4rem;">{tip}</div>', unsafe_allow_html=True)

    hotel_sum = plan.get("hotel_summary", "")
    if hotel_sum:
        st.markdown('<div style="font-weight:600; font-size:0.88rem; color:#374151; margin:1rem 0 0.4rem;">AI Analysis</div>', unsafe_allow_html=True)
        st.markdown(f'<div class="card"><div style="font-size:0.86rem; color:#374151; line-height:1.75; white-space:pre-line;">{hotel_sum}</div></div>', unsafe_allow_html=True)


# ── TAB 3 · Itinerary ─────────────────────────────────────────────────────────
with tabs[3]:
    itinerary_text = (plan.get("itinerary") or "").strip()
    if not itinerary_text:
        st.info("Itinerary not available.")
    else:
        # Parse day blocks
        lines   = itinerary_text.split("\n")
        current: list[str] = []
        blocks:  list[list[str]] = []

        for line in lines:
            stripped = line.strip()
            is_day_header = (
                stripped.lower().startswith("day ")
                and len(stripped) > 4
                and stripped[4:6].strip().rstrip(":").isdigit()
            )
            if is_day_header and current:
                blocks.append(current)
                current = [line]
            elif stripped:
                current.append(line)
        if current:
            blocks.append(current)

        DAY_COLORS = [
            "#1d4ed8", "#7c3aed", "#d97706", "#15803d", "#dc2626",
            "#0891b2", "#be185d", "#4f46e5", "#0d9488", "#92400e",
        ]

        if blocks:
            for i, block in enumerate(blocks):
                color  = DAY_COLORS[i % len(DAY_COLORS)]
                header = block[0].strip()
                body   = "\n".join(line for line in block[1:] if line.strip())
                st.markdown(f"""
                <div class="day-block" style="border-left-color:{color};">
                  <div class="day-header" style="color:{color};">{header}</div>
                  <div class="day-body">{body}</div>
                </div>
                """, unsafe_allow_html=True)
        else:
            # Fallback: just render as text
            st.markdown(f'<div class="card"><div style="font-size:0.86rem; color:#374151; line-height:1.75; white-space:pre-line;">{itinerary_text}</div></div>', unsafe_allow_html=True)


# ── TAB 4 · Budget ────────────────────────────────────────────────────────────
with tabs[4]:
    labels = ["Flights", "Accommodation", "Food", "Transport", "Activities", "Misc"]
    values = [
        float(bd.get("flights") or 0),
        float(bd.get("accommodation") or 0),
        float(bd.get("food") or 0),
        float(bd.get("local_transport") or 0),
        float(bd.get("activities") or 0),
        float(bd.get("miscellaneous") or 0),
    ]
    chart_colors = ["#1d4ed8", "#7c3aed", "#d97706", "#15803d", "#dc2626", "#9ca3af"]
    transparent  = "rgba(0,0,0,0)"
    base_layout  = dict(
        paper_bgcolor=transparent,
        plot_bgcolor=transparent,
        font=dict(color="#374151", family="Inter", size=11),
        margin=dict(t=38, b=18, l=8, r=8),
    )

    c1, c2 = st.columns(2)

    with c1:
        fig = go.Figure(go.Pie(
            labels=labels,
            values=values,
            hole=0.6,
            marker=dict(colors=chart_colors, line=dict(color="#ffffff", width=2)),
            textfont=dict(size=11),
            hovertemplate="<b>%{label}</b><br>Rs %{value:,.0f}<br>%{percent}<extra></extra>",
        ))
        fig.update_layout(
            **base_layout,
            title=dict(text="Budget Breakdown", font=dict(size=13, color="#111827")),
            legend=dict(bgcolor=transparent, font=dict(color="#6b7280", size=11)),
            annotations=[dict(
                text=f"Rs {total_est:,.0f}", x=0.5, y=0.5,
                font=dict(size=12, color="#111827"), showarrow=False,
            )],
        )
        st.plotly_chart(fig, use_container_width=True)

    with c2:
        random.seed(42)
        daily_avg  = float(bd.get("daily_average") or 2000)
        daily_vals = [round(daily_avg * random.uniform(0.75, 1.3)) for _ in range(days_val)]
        day_labels = [f"Day {i+1}" for i in range(days_val)]

        fig2 = go.Figure(go.Bar(
            x=day_labels, y=daily_vals,
            marker=dict(
                color=daily_vals,
                colorscale=[[0, "#dbeafe"], [0.5, "#2563eb"], [1, "#1e3a5f"]],
                line=dict(width=0),
            ),
            hovertemplate="<b>%{x}</b><br>Rs %{y:,.0f}<extra></extra>",
        ))
        fig2.update_layout(
            **base_layout,
            title=dict(text="Estimated Daily Spend", font=dict(size=13, color="#111827")),
            xaxis=dict(gridcolor="#f3f4f6", tickfont=dict(color="#9ca3af")),
            yaxis=dict(gridcolor="#f3f4f6", tickfont=dict(color="#9ca3af"), tickprefix="Rs "),
            bargap=0.3,
        )
        st.plotly_chart(fig2, use_container_width=True)

    c3, c4 = st.columns(2)

    with c3:
        fig3 = go.Figure(go.Sunburst(
            labels=["Total"] + labels,
            parents=[""] + ["Total"] * len(labels),
            values=[total_est] + values,
            branchvalues="total",
            marker=dict(colors=["#f9fafb"] + chart_colors),
            hovertemplate="<b>%{label}</b><br>Rs %{value:,.0f}<extra></extra>",
            textfont=dict(size=11),
        ))
        fig3.update_layout(
            **base_layout,
            title=dict(text="Cost Distribution", font=dict(size=13, color="#111827")),
        )
        st.plotly_chart(fig3, use_container_width=True)

    with c4:
        gv   = min(utilization, 100)
        gcol = "#15803d" if gv < 70 else "#d97706" if gv < 90 else "#dc2626"
        fig4 = go.Figure(go.Indicator(
            mode="gauge+number",
            value=gv,
            number={"suffix": "%", "font": {"color": gcol, "size": 30, "family": "Inter"}},
            gauge={
                "axis": {"range": [0, 100], "tickfont": {"color": "#9ca3af", "size": 10}},
                "bar":  {"color": gcol, "thickness": 0.22},
                "bgcolor": "#f9fafb", "borderwidth": 0,
                "steps": [
                    {"range": [0,  70], "color": "#f0fdf4"},
                    {"range": [70, 90], "color": "#fff7ed"},
                    {"range": [90,100], "color": "#fef2f2"},
                ],
                "threshold": {"line": {"color": "#374151", "width": 2}, "value": 80},
            },
        ))
        fig4.update_layout(
            **base_layout,
            title=dict(text="Budget Utilization", font=dict(size=13, color="#111827")),
            height=280,
        )
        st.plotly_chart(fig4, use_container_width=True)

    budget_sum = plan.get("budget_summary", "")
    if budget_sum:
        st.markdown('<div style="font-weight:600; font-size:0.88rem; color:#374151; margin:0.5rem 0 0.4rem;">AI Budget Analysis</div>', unsafe_allow_html=True)
        st.markdown(f'<div class="card"><div style="font-size:0.86rem; color:#374151; line-height:1.75; white-space:pre-line;">{budget_sum}</div></div>', unsafe_allow_html=True)


# ── TAB 5 · Recommendations ───────────────────────────────────────────────────
with tabs[5]:
    recs = (plan.get("recommendations") or "").strip()
    if not recs:
        st.info("Recommendations not available.")
    else:
        # Parse sections by known headings
        HEADINGS = {
            "TOP RESTAURANTS": "#d97706",
            "RESTAURANTS":     "#d97706",
            "TOP ATTRACTIONS": "#1d4ed8",
            "ATTRACTIONS":     "#1d4ed8",
            "HIDDEN GEMS":     "#7c3aed",
            "TRAVEL TIPS":     "#15803d",
            "SHOPPING":        "#dc2626",
        }

        current_heading = ""
        current_color   = "#6b7280"
        current_body:   list[str] = []
        sections:       list[tuple[str, str, str]] = []

        for line in recs.split("\n"):
            stripped = line.strip()
            matched  = False
            for hdr, color in HEADINGS.items():
                if stripped.upper().startswith(hdr):
                    if current_heading:
                        sections.append((current_heading, current_color,
                                         "\n".join(current_body).strip()))
                    current_heading = stripped
                    current_color   = color
                    current_body    = []
                    matched = True
                    break
            if not matched and stripped:
                current_body.append(line)
        if current_heading:
            sections.append((current_heading, current_color,
                             "\n".join(current_body).strip()))

        if sections:
            left_secs  = sections[::2]
            right_secs = sections[1::2]
            cl, cr = st.columns(2, gap="medium")
            for sec in left_secs:
                hdr, color, body = sec
                with cl:
                    st.markdown(f"""
                    <div class="rec-section" style="border-top-color:{color};">
                      <div class="rec-header" style="color:{color};">{hdr}</div>
                      <div class="rec-body">{body}</div>
                    </div>
                    """, unsafe_allow_html=True)
            for sec in right_secs:
                hdr, color, body = sec
                with cr:
                    st.markdown(f"""
                    <div class="rec-section" style="border-top-color:{color};">
                      <div class="rec-header" style="color:{color};">{hdr}</div>
                      <div class="rec-body">{body}</div>
                    </div>
                    """, unsafe_allow_html=True)
        else:
            st.markdown(f'<div class="card"><div style="font-size:0.86rem; color:#374151; line-height:1.75; white-space:pre-line;">{recs}</div></div>', unsafe_allow_html=True)


# ── TAB 6 · Export ────────────────────────────────────────────────────────────
with tabs[6]:
    serializable = {
        k: v for k, v in plan.items()
        if isinstance(v, (str, int, float, dict, list, bool, type(None)))
    }
    safe_dest = dest.replace(" ", "_").lower()

    ex1, ex2, ex3 = st.columns(3)

    with ex1:
        st.markdown('<div class="card">', unsafe_allow_html=True)
        st.markdown("**JSON Export**")
        st.markdown('<div style="font-size:0.77rem; color:#9ca3af; margin-bottom:0.8rem;">Full structured plan data</div>', unsafe_allow_html=True)
        st.download_button(
            "Download JSON",
            data=json.dumps(serializable, indent=2, ensure_ascii=False),
            file_name=f"trip_{safe_dest}.json",
            mime="application/json",
            use_container_width=True,
        )
        st.markdown("</div>", unsafe_allow_html=True)

    with ex2:
        st.markdown('<div class="card">', unsafe_allow_html=True)
        st.markdown("**Text Export**")
        st.markdown('<div style="font-size:0.77rem; color:#9ca3af; margin-bottom:0.8rem;">Plain-text report</div>', unsafe_allow_html=True)
        st.download_button(
            "Download TXT",
            data=_build_text_report(plan),
            file_name=f"trip_{safe_dest}.txt",
            mime="text/plain",
            use_container_width=True,
        )
        st.markdown("</div>", unsafe_allow_html=True)

    with ex3:
        st.markdown('<div class="card">', unsafe_allow_html=True)
        st.markdown("**PDF Export**")
        st.markdown('<div style="font-size:0.77rem; color:#9ca3af; margin-bottom:0.8rem;">Formatted document</div>', unsafe_allow_html=True)
        if st.button("Generate PDF", use_container_width=True):
            with st.spinner("Building PDF..."):
                pdf_bytes = _generate_pdf(plan)
            if pdf_bytes:
                st.download_button(
                    "Download PDF",
                    data=pdf_bytes,
                    file_name=f"trip_{safe_dest}.pdf",
                    mime="application/pdf",
                    use_container_width=True,
                )
            else:
                st.warning("reportlab not installed. Run: pip install reportlab")
        st.markdown("</div>", unsafe_allow_html=True)

    with st.expander("View Raw JSON"):
        st.json(serializable)